---

name: Trigger Target Workflow2

on:
  workflow_dispatch:

jobs:
  my_job:
    name: Send a Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install gha-token
        run: python3.11 -m pip install "git+https://github.com/hypothesis/gha-token.git"
      - name: Get GitHub token
        id: github_token
        run: echo GITHUB_TOKEN=$(gha-token --app-id 1107154 --installation-id 59359748 --private-key "$PRIVATE_KEY") >> $GITHUB_OUTPUT
        env:
          PRIVATE_KEY: ${{ secrets.MY_GITHUB_APP_PRIVATE_KEY }}
      - name: Token
        run: echo "${GH_TOKEN}"
        env:
          GH_TOKEN: ${{ steps.github_token.outputs.GITHUB_TOKEN }}
      - name: Trigger
        run: gh workflow run --repo nzolot/repo-dst
        env:
          GH_TOKEN: ${{ steps.github_token.outputs.GITHUB_TOKEN }}
